/* ============================================================
   FinTrack — PDF Export
   Builds a financial report PDF from the currently selected
   Analytics period + wallet, with Download and Share options.
   ============================================================ */

function buildReportDoc() {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();
  const data = getAnalytics(currentPeriod, currentWallet);
  const walletLabel = currentWallet === 'aed' ? 'Dubai (AED)' : 'India (INR)';
  const sym = currentWallet === 'aed' ? 'AED ' : 'Rs. ';
  const periodLabel = currentPeriod.charAt(0).toUpperCase() + currentPeriod.slice(1);

  // Header
  doc.setFillColor(13, 19, 33);
  doc.rect(0, 0, 210, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('FinTrack', 14, 14);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(212, 175, 55);
  doc.text('Track Today, Grow Tomorrow', 14, 21);

  doc.setTextColor(20, 20, 20);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text(`${periodLabel} Report — ${walletLabel}`, 14, 40);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`, 14, 46);

  // Income vs Expense summary boxes
  let y = 56;
  doc.setDrawColor(220, 220, 220);
  doc.setFillColor(240, 248, 245);
  doc.roundedRect(14, y, 85, 26, 2, 2, 'F');
  doc.setFillColor(250, 240, 240);
  doc.roundedRect(111, y, 85, 26, 2, 2, 'F');

  doc.setFontSize(9);
  doc.setTextColor(46, 125, 107);
  doc.text('INCOME', 20, y + 8);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`${sym}${data.income.toLocaleString('en-IN')}`, 20, y + 18);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(192, 91, 77);
  doc.text('EXPENSE', 117, y + 8);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`${sym}${data.expense.toLocaleString('en-IN')}`, 117, y + 18);

  y += 34;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(data.net >= 0 ? 46 : 192, data.net >= 0 ? 125 : 91, data.net >= 0 ? 107 : 77);
  doc.text(`Net: ${data.net >= 0 ? '+' : '-'}${sym}${Math.abs(data.net).toLocaleString('en-IN')}`, 14, y);

  // Category breakdown table
  y += 12;
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(11);
  doc.text('Spending by Category', 14, y);
  y += 6;

  if (data.categories.length === 0) {
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.setFont('helvetica', 'normal');
    doc.text('No expenses recorded in this period.', 14, y + 4);
    y += 10;
  } else {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(120, 120, 120);
    doc.text('Category', 14, y);
    doc.text('Amount', 130, y);
    doc.text('%', 175, y);
    y += 4;
    doc.setDrawColor(220, 220, 220);
    doc.line(14, y, 196, y);
    y += 5;

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(40, 40, 40);
    data.categories.forEach(c => {
      doc.text(c.name, 14, y);
      doc.text(`${sym}${c.amount.toLocaleString('en-IN')}`, 130, y);
      doc.text(`${c.pct}%`, 175, y);
      y += 6;
    });
    y += 4;
  }

  // Cash flow table
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(20, 20, 20);
  doc.text('Cash Flow', 14, y);
  y += 6;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  data.cashflow.forEach(c => {
    doc.setTextColor(40, 40, 40);
    doc.text(c.label, 14, y);
    doc.setTextColor(c.net >= 0 ? 46 : 192, c.net >= 0 ? 125 : 91, c.net >= 0 ? 107 : 77);
    doc.text(`${c.net >= 0 ? '+' : '-'}${sym}${Math.abs(c.net).toLocaleString('en-IN')}`, 130, y);
    y += 6;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(160, 160, 160);
  doc.text('Generated by FinTrack — local & Supabase-synced expense tracker', 14, 287);

  return doc;
}

function downloadReportPDF() {
  const doc = buildReportDoc();
  const filename = `fintrack-report-${currentPeriod}-${currentWallet}-${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}

async function shareReportPDF() {
  const doc = buildReportDoc();
  const filename = `fintrack-report-${currentPeriod}-${currentWallet}.pdf`;
  const blob = doc.output('blob');
  const file = new File([blob], filename, { type: 'application/pdf' });

  if (navigator.canShare && navigator.canShare({ files: [file] })) {
    try {
      await navigator.share({
        files: [file],
        title: 'FinTrack Report',
        text: `My ${currentPeriod} FinTrack report`
      });
    } catch (err) {
      // User cancelled the share sheet — no action needed
    }
  } else {
    // Fallback for desktop browsers without file-sharing support
    doc.save(filename);
    alert('Sharing isn\'t supported on this browser — the PDF was downloaded instead. On your phone, this button opens the native share sheet.');
  }
}

document.addEventListener('DOMContentLoaded', () => {
  const dlBtn = document.getElementById('downloadPdfBtn');
  const shareBtn = document.getElementById('sharePdfBtn');
  if (dlBtn) dlBtn.addEventListener('click', downloadReportPDF);
  if (shareBtn) shareBtn.addEventListener('click', shareReportPDF);
});
